#!/usr/bin/env zsh

alias vim="nvim"
alias sl="ls"
alias ivm="nvim"
alias hack.exe="export GREP_COLOR='1;32'; cat /dev/urandom | hexdump -C | grep --color=auto \"ca fe\""
alias myip="curl ifconfig.me"
alias netscan="arp-scan --interface=en0 --localnet"
alias rs="npm run-script"
alias serve="http-server ."
alias aws="aws-3.7"
alias getuuid='uuidgen | tr "[:upper:]" "[:lower:]"'

UNAME=$(uname)
UNAME_A=$(uname -a)

if [[ "$UNAME" == "Darwin" ]]; then
  alias copy="pbcopy <"
  alias ls="gls --color=auto --group-directories-first -lA"
  alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
elif [[ "$UNAME" == "Linux" ]]; then
  alias copy="xclip -selection c"
  alias ls="ls --color=auto --group-directories-first -lA"

  # Is this Windows Subsytem for Linux?
  if [[ "$UNAME_A" == *"Microsoft"* ]]; then
    # https://github.com/4U6U57/wsl-open
    alias open="wsl-open >/dev/null 2>&1"
    alias xdg-open="open"
  else
    alias open="xdg-open >/dev/null 2>&1"
  fi
fi

alias kubedev='export KUBECONFIG=~/.kube/kubeconfig-dev-sandbox-redux'
alias kubeplayground='export KUBECONFIG=~/.kube/kubeconfig-playground-sandbox'
alias kubestaging='export KUBECONFIG=~/.kube/kubeconfig-arryn-staging-redux'
alias kubeweb='export KUBECONFIG=~/.kube/kubeconfig-greyjoy-production'
alias kubebeta='export KUBECONFIG=~/.kube/kubeconfig-tully-beta'
alias kubewebsingapore='export KUBECONFIG=~/.kube/kubeconfig-greyjoy-production-singapore'
alias kubeprod='export KUBECONFIG=~/.kube/kubeconfig-stark-production'

