#!/usr/bin/env zsh

# Get the available versions of an npm package

JQ=$(which jq)

if [ -z "$JQ" ]; then
  echo "Install jq plz"
  exit 1
fi

PACKAGE=${@: -1}

if [ -z "$PACKAGE" ]; then
  echo "I need a package to look up..."
  exit 1
fi

npm view "$PACKAGE" --json | \
  jq -r '{versions} | .[] | .[]'
